version: "3"
services:
  go-upload-progress-backend:
    build: .
    environment:
      SERVER_ADDRESS: ":8080"
      PUBLIC_FILE_DIR: /var/www/go-upload-progress-backend
      UPLOADED_FILE_DIR: /opt/go-upload-progress-backend/files
    ports:
      - 8080:8080
    volumes:
      - ./public:/var/www/go-upload-progress-backend
      - ./files:/opt/go-upload-progress-backend/files
